import "./globals.css";
import { Roboto } from "next/font/google";
import { Header } from "./components/Header";
import Head from "next/head";


const roboto = Roboto({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  

  return (
    <html lang="en">
      <Head>
        <style>{roboto.styles}</style>
      </Head>
      <body>
        <Header />
        <main >{children}</main>
      </body>
    </html>
  );
}
